apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-price-api
  namespace: ml-housing-app
  labels:
    app: housing-price-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: housing-price-api
  template:
    metadata:
      labels:
        app: housing-price-api
    spec:
      containers:
      - name: housing-price-api
        image: housingpriceregistry.azurecr.io/housing-price-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/models"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      imagePullSecrets:
      - name: acr-secret